# Site settings
title: The Jewelry Appraiser
email: deborah@thejewelryappraiser.com
description: Jewelry appraisals by the jewelry appraiser – Independent Certified Gemologist Appraiser (ICGA) and private gemology lab in Manhasset, NY
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://thejewelryappraiser.com" # the base hostname & protocol for your site
twitter_username: NYAppraiserDeb

# Build settings
markdown: kramdown
