# Site settings
title: Alex's Lab
email: alexlib@tau.ac.il
description: Research Laboratory, Tel Aviv University, experimental turbulence
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://alex-lab.github.io" # the base hostname & protocol for your site
twitter_username: alexlib
github_username:  alexlib

# Build settings
markdown: kramdown
